#version: '2'
#services:
#  web:
#    build:
#      context: .
#    restart: always
#    ports:
#      - "10054:8080"
#    volumes:
#      - ./file-storage:/file-storage
#      - ./log:/log
#    env_file:
#      - app.env
#    depends_on:
#      - db
#    networks:
#      - frontend-network
#      - backend-network
#
#  db:
#    image: mariadb:10.4.24
#    restart: always
#    env_file:
#      - app.env
#    volumes:
#      - mysql-db-volume:/var/lib/mysql
#    networks:
#      - backend-network
#
#volumes:
#  mysql-db-volume:
#
#networks:
#  frontend-network:
#    driver: bridge
#  backend-network:

version: '2'
services:
  web:
    image: apap-registry.cs.ui.ac.id/muhammad.rafi07/tk-apap-054
    restart: always
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - app.env
    depends_on:
      - db
    ports:
      - 10054:8080
    networks:
      - frontend-network
      - backend-network

  db:
    image: mariadb:10.4.24
    restart: always
    env_file:
      - app.env
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql-db-volume:

networks:
  frontend-network:
    driver: bridge
  backend-network:

